# custom rules here

SecRule REQUEST_URI "@contains __custom_test__" "id:990001,phase:2,deny,status:403,log,msg:'CUSTOM RULE HIT'"

SecRule REQUEST_URI "@contains __auto_deploy_test__" "id:990002,phase:2,deny,status:403,log,msg:AUTO_DEPLOY_TEST_RULE_HIT"
